spring:
  datasource:
    url: ${DEV_SPRING_DATASOURCE_URL}
    username: ${DEV_SPRING_DATASOURCE_USERNAME}
    password: ${DEV_SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # auto-update schema in dev
    show-sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    root: INFO
    org.hibernate.bytecode.internal.bytebuddy: INFO
    org.springframework.security: DEBUG



cloud:
  function:
    aws:
      stack:
        url: http://localhost:5000
      accessKey: test
      secretKey: test
      region: us-east-1
      analyticsEndpoint: http://localhost:5000/consolidated-analytics/
      comparisonEndpoint: http://localhost:5000/comparision/

