spring:
  datasource:
    url: ${DEV_SPRING_DATASOURCE_URL}
    username: ${DEV_SPRING_DATASOURCE_USERNAME}
    password: ${DEV_SPRING_DATASOURCE_PASSWORD}
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    root: ERROR
    org.hibernate: ERROR
    org.springframework: ERROR
  config: classpath:logback-spring.xml


