spring:
  datasource:
    url: ${DEV_SPRING_DATASOURCE_URL}
    username: ${DEV_SPRING_DATASOURCE_USERNAME}
    password: ${DEV_SPRING_DATASOURCE_PASSWORD}
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.arian.vizpotifybackend: DEBUG
    root: ERROR
#    org.hibernate: ERROR
#    org.springframework: ERROR


  config: classpath:logback-spring.xml

server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always



