spring:
  jpa:
    hibernate:
      ddl-auto: update  # auto-update schema in dev
    show-sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    root: DEBUG  # More verbose logging in development

