spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  devtools:
#    remote:
#      secret: mysecret
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
       ddl-auto: validate
       dialect: org.hibernate.dialect.PostgreSQLDialect
       default_schema: public
       jdbc:
         batch_size: 20
         fetch_size: 20
    show-sql: true
  cache:
    type: none
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
fastapi:
  base-url: http://localhost:8000
#logging:
#  level:
#    org:
#      hibernate:
#        SQL:
#        type:
#          descriptor:
#            sql:
#
#    jdbc:
#      sqltiming: DEBUG
#      resultsettable: DEBUG
spotify:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  redirectUri: ${REDIRECT_URI}
  scopes:
    - user-follow-read
    - playlist-read-collaborative
    - user-library-read
    - user-top-read
    - user-read-playback-state
    - user-read-recently-played
jwt:
  secretKey: 3qRU5Tu7qho8Wj/GjKLzoc8laOPJHERxHu9NnL8dzYbcwOS2XWftAZ2jNjoNbSvR
  validityInMs: 36000000
misc:
  frontendUrl: http://localhost:3000
